### ISSUE TITLE
When attempting to search anything with velocity or nodeunblocker, it just 

### ISSUE THREAD

**Issue by xlrunsyou** [CrossScarDev/UBTW2#2]
![image](https://github.com/CommanderGL/UBTW2/assets/115091379/cd0cdeec-2659-4d9b-8239-cd4dcdb82bd1)
It Just shows a screen that I cannot connect to the desired site.

**Comment by Codeiology** [comment]
Same thing here. Velocity works, but whenever you want to search anything it returns a typerror and breaks.

**Comment by CommanderGL** [comment]
just go to google.com then search. IDK why this happens but it's no special to github codespaces. If this solves your problem pls close this issue.

**Comment by CrossScarDev** [comment]
Closing this issue as stale.
